@echo on
::This script will generate a list of all users logged into a computer. This will then change all users' passwords to one set password.
::You can change the password to be set by modifying the "newpassword" variable and deleting the placeholder, "YourNewPassword"
::Use this for CP competitions
::Generated by ChatGPT

setlocal enabledelayedexpansion

rem Define the new password
set newpassword=RBRHS2026!

rem Get a list of all user accounts
for /f "skip=1" %%i in ('net user ^| find /v "The command completed successfully."') do (
    set "user=%%i"
    rem Extract the username from the line
    for /f "tokens=1" %%j in ("!user!") do (
        set username=%%j
        rem Change the password for each user
        net user !username! !newpassword!
        if !errorlevel! equ 0 (
            echo Password for !username! changed successfully.
        ) else (
            echo Failed to change the password for !username!.
        )
    )
)

endlocal
